# GitHub repository configuration for Pomodux
# This file configures issue templates and repository settings

# Issue template chooser configuration
blank_issues_enabled: false
contact_links:
  - name: Pomodux Documentation
    url: https://github.com/rsmacapinlac/pomodux/tree/main/docs
    about: Please check the documentation before creating an issue. 