run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/
    - third_party/
    - test/

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - goimports
    - gocyclo
    - dupl
    - goconst

linters-settings:
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl 